# Use REST Client Extension VSCode
@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjkwMDk1YmM2ZGM2ZDY3NzkxZDdkYTFlZWIxYTU1OWEzZDViMmM0ODYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZmItZnVsbHN0YWNrIiwiYXVkIjoiZmItZnVsbHN0YWNrIiwiYXV0aF90aW1lIjoxNjI5OTYwMjM2LCJ1c2VyX2lkIjoiTTVSNHl3UVNBRWVEVzJOZlVQNEZ1ejdMUVJDMyIsInN1YiI6Ik01UjR5d1FTQUVlRFcyTmZVUDRGdXo3TFFSQzMiLCJpYXQiOjE2Mjk5NjAyMzYsImV4cCI6MTYyOTk2MzgzNiwiZW1haWwiOiJ0ZWZsb25AZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlZmxvbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.SxjL6xiQs6IjXTyi1ueBtWqyzBHn6gL68ZVbdSne7AMNbYI926Z84ZtDN4ppz5FLMsynOE9JPcPzjMpqxhdhLUjCNPLemJTX21if2O_SIgjvZVahxUBYAuMAj6C4Ts-Q5gW-DMOONSqMrDNEXvNxcnFob6RJpXTkNVqFHUBMzdrPFkAlZ5gjUp7lvnfM-52MSgZvHTyUaK-6vU-OiPEmcB1zjn0mjB8A-TVGkV-NsRM16Jn8Kdjqno6INgyCKjZKuncjtROEyOekHmkkq-XreTsNw_hT_kJXmRr836SdKnCwMtWBPITWsvdO4yPN7IBiaBD7w45FFNjbp8wIJFd4ZA
@baseUrl = http://localhost:5000/fb-fullstack/us-central1/api/post
### Create Post
POST {{baseUrl}}
content-type: application/json
Authorization: Bearer {{token}}

{
	"body": "New post...",
	"userHandle": "teflondon"
}